// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"hackerrank/repositories"
	"hackerrank/robot-en-marte/ctx"
)

// Injectors from wire.go:

func Initialize() (*ctx.Handler, error) {
	intruccion := repositories.NewIntruccionRepository()
	handler := ctx.NewHandler(intruccion)
	return handler, nil
}
