// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"hackerrank/numero-elementos/ctx"
	"hackerrank/repositories"
)

// Injectors from wire.go:

func Initialize() (*ctx.Handler, error) {
	cleanList := repositories.NewCleanList()
	handler := ctx.NewHandler(cleanList)
	return handler, nil
}
